<?php
	declare(strict_types=1); //Created at 2019-06-18 05:12:41 by 16904

	namespace Framework\Application\UtilitiesV2\Makers;

	use Framework\Application;
	use Framework\Application\UtilitiesV2\Conventions\FileData;
	use Framework\Application\UtilitiesV2\FileOperator;
	use Framework\Application\UtilitiesV2\Conventions\TokenData;
	use Framework\Application\UtilitiesV2\Format;

	/**
	 * Class Job
	 * @package Framework\Application\UtilitiesV2\Makers
	 */
	class Job extends Base
	{

		/**
		 * @package FileData|null $template
		 */

		public function before(FileData $template = null): void
		{

			if ($template == null)
				$template = FileOperator::pathDataInstance("resources/templates/template_" . strtolower("Job" ) . ".module");

			parent::before($template);
		}

		/**
		 * @package TokenData $values
		 * @param $path
		 *
		 * @package FileData
		 */

		public function make(TokenData $values, $path): FileData
		{

			/**
			 * the TokenData class holds the values which we will be inserting into our template. It also holds key information
			 * like the class name.
			 *
			 * $values->arrayValue("values", "classname") //Class Name
			 * $values->arrayValue("values", "time") //Current Time
			 * $values->arrayValue("values", "namespace") //Namespace
			 */

			return parent::make($values, $path); // TODO: Change the autogenerated stub
		}

		/**
		 * @package string
		 */

		public function filepath(): string
		{

			return( Application::globals()->PIPELINE_FILEPATH );
		}

		/**
		 * @package string
		 */

		public function namespace(): string
		{

			return( Format::rc( Application::globals()->PIPELINE_NAMESPACE ) );
		}
	}