<?php
	/**
	 * Created by PhpStorm.
	 * User: newsy
	 * Date: 20/06/2019
	 * Time: 21:17
	 */

	namespace Framework\Tests;

	use Framework\Views\ControllerV3;

	class ControllerV3Test extends BaseTestCase
	{

		/**
		 * @var ControllerV3
		 */

		protected static $controller;

		public static function setUpBeforeClass(): void
		{

			if( isset( self::$controller ) == false )
				self::$controller = new ControllerV3();

			parent::setUpBeforeClass(); // TODO: Change the autogenerated stub
		}

		public function testRun()
		{

			self::$controller->run();

			self::assertTrue( self::$controller::$successful );
		}
	}
