<?php
	declare(strict_types=1);
	/**
	 * Created by PhpStorm.
	 * User: newsy
	 * Date: 15/05/2019
	 * Time: 01:37
	 */

	namespace Framework\Tests;

	use Framework\Syscrack\Game\Items;

	/**
	 * Class ItemsTest
	 * @package Framework\Tests
	 */
	class ItemsTest extends BaseTestCase
	{

		/**
		 * @var Items
		 */

		protected static $items;
		protected static $item = 'colours';

		public static function setUpBeforeClass(): void
		{

			if( isset( self::$items ) == false )
				self::$items = new Items();

			parent::setUpBeforeClass(); // TODO: Change the autogenerated stub
		}

		public function testItem()
		{

			static::assertNotEmpty( self::$items->item(self::$item) );

		}

		public function testHas()
		{

			static::assertTrue( self::$items->has(self::$item) );
		}

		public function testTraded()
		{

			static::assertTrue( self::$items->traded(self::$item,0,0,0) );
		}

		public function testUsed()
		{

			static::assertTrue( self::$items->used(self::$item,0,0,0) );
		}

		public function testEquipped()
		{

			static::assertTrue( self::$items->equipped(self::$item,0,0,0) );
		}

		public function testSettings()
		{

			static::assertNotEmpty( self::$items->settings(self::$item) );
		}
	}
