<?php
	/**
	 * Created by PhpStorm.
	 * User: newsy
	 * Date: 20/06/2019
	 * Time: 00:45
	 */

	namespace Framework\Tests;

	use Framework\Syscrack\Game\ModLoader;
	use PHPUnit\Framework\TestCase;

	class ModLoaderTest extends BaseTestCase
	{

		/**
		 * @var ModLoader
		 */

		protected static $modloader;

		public static function setUpBeforeClass(): void
		{

			if( isset( self::$modloader ) == false )
				self::$modloader = new ModLoader();

			parent::setUpBeforeClass(); // TODO: Change the autogenerated stub
		}

		public function testGet()
		{

			self::assertTrue( ModLoader::hasInitialized() );
		}
	}
