<?php
	/**
	 * Created by PhpStorm.
	 * User: newsy
	 * Date: 22/05/2019
	 * Time: 14:40
	 */

	namespace Framework\Tests;

	use Framework\Syscrack\Game\SoftwareTypes;

	class SoftwareTypesTest extends BaseTestCase
	{

		/**
		 * @var SoftwareTypes
		 */

		protected static $softwaretypes;

		/**
		 *
		 */

		public static function setUpBeforeClass(): void
		{

			if( isset( self::$softwaretypes ) == false )
				self::$softwaretypes = new SoftwareTypes();

			parent::setUpBeforeClass(); // TODO: Change the autogenerated stub
		}

		/**
		 *
		 */

		public function testGet()
		{

			$this->assertNotEmpty( self::$softwaretypes->get() );
		}
	}
