<?php
	/**
	 * Created by PhpStorm.
	 * User: newsy
	 * Date: 15/05/2019
	 * Time: 01:45
	 */

	namespace Framework\Tests;

	use Framework\Syscrack\Game\Tab;
	use Framework\Syscrack\Game\Tabs;

	class TabsTest extends BaseTestCase
	{

		/**
		 * @var Tabs
		 */

		protected static $tabs;

		public static function setUpBeforeClass(): void
		{

			if( isset( self::$tabs )  == false  )
				self::$tabs = new Tabs();

			parent::setUpBeforeClass(); // TODO: Change the autogenerated stub
		}


		public function testAdd()
		{

			$tab = new Tab('default') ;
			$tab->postMethod(function(){
				return true;
			});
			$tab->dataMethod(function(){
				return true;
			});

			self::$tabs->add( $tab );
			$this->assertNotEmpty( self::$tabs->get() );
		}

		public function testPost()
		{

			$this->assertTrue( self::$tabs->post('default',0,0,0) );
		}

		public function testData()
		{

			$this->assertTrue( self::$tabs->data('default',0,0,0) );
		}
	}
