<?php
	/**
	 * Created by PhpStorm.
	 * User: newsy
	 * Date: 15/05/2019
	 * Time: 01:46
	 */

	namespace Framework\Tests;

	use Framework\Syscrack\Game\Tab;

	class TabTest extends BaseTestCase
	{

		/**
		 * @var Tab
		 */

		protected static $tab;

		public static function setUpBeforeClass(): void
		{

			if( isset( self::$tab ) == false )
				self::$tab = new Tab();

			parent::setUpBeforeClass(); // TODO: Change the autogenerated stub
		}

		public function testRender()
		{

			self::$tab->render('test', []);
			$this->assertTrue( self::$tab->hasRender() );
		}


		public function testCanPost()
		{

			self::$tab->postMethod( function(){} );
			$this->assertTrue( self::$tab->canPost() );
		}

		public function testHasDataMethod()
		{

			self::$tab->dataMethod( function(){} );
			$this->assertTrue( self::$tab->hasDataMethod() );
		}

		public function testInputData()
		{

			self::$tab->add( Tab::InputData([
				'name' => 'test',
				'type' => 'test',
				'value' => 'test',
				'placeholder' => 'test'
			]));
			$this->assertTrue( self::$tab->hasInputs() );
		}


		public function testName()
		{

			$this->assertNotEmpty( self::$tab->name() );
		}

		public function testHasRender()
		{

			$this->assertTrue( self::$tab->hasRender() );
		}
	}
