<?php
	declare(strict_types=1);
	/**
	 * Created by PhpStorm.
	 * User: newsy
	 * Date: 01/05/2019
	 * Time: 15:14
	 */

	namespace Framework\Tests;

	use Framework\Syscrack\Game\Themes;

	/**
	 * Class ThemesTest
	 * @package Framework\Tests
	 */
	class ThemesTest extends BaseTestCase
	{

		/**
		 * @var Themes
		 */

		protected static $themes;
		protected static $theme = 'bootstrap4';

		public static function setUpBeforeClass(): void
		{

			self::$themes = new Themes(false);
			parent::setUpBeforeClass(); // TODO: Change the autogenerated stub
		}

		public function testCurrentTheme()
		{

			static::assertNotEmpty(self::$themes->currentTheme());
		}

		public function testGather()
		{

			$folders = self::$themes->getFolders();

			static::assertNotEmpty($folders);
			static::assertNotEmpty(self::$themes->gather($folders));
		}

		public function testGetTheme()
		{

			self::$themes->getThemes();
			static::assertNotEmpty(self::$themes->getTheme(self::$theme));
		}

		public function testGetData()
		{

			self::$themes->getThemes();
			static::assertNotEmpty(self::$themes->getData(self::$theme));
		}

		public function testGetThemes()
		{

			$result = self::$themes->getThemes();
			static::assertNotEmpty($result);
		}

		public function testThemeExists()
		{

			self::$themes->getThemes();
			static::assertTrue(self::$themes->themeExists(self::$theme));
		}

		public function testGetFolders()
		{

			static::assertNotEmpty(self::$themes->getFolders());
		}
	}
