<?php
	declare(strict_types=1);
	/**
	 * Created by PhpStorm.
	 * User: newsy
	 * Date: 05/05/2019
	 * Time: 21:38
	 */

	namespace Framework\Tests;

	use Framework\Syscrack\Game\Types;

	/**
	 * Class TypesTest
	 * @package Framework\Tests
	 */
	class TypesTest extends BaseTestCase
	{

		/**
		 * @var Types
		 */

		protected static $types;

		public static function setUpBeforeClass(): void
		{

			self::$types = new Types();
			parent::setUpBeforeClass(); // TODO: Change the autogenerated stub
		}

		public function testGet()
		{

			static::assertNotEmpty(self::$types->get());
		}
	}
