<?php
	declare(strict_types=1); //Created at 2019-06-11 03:15:36 by 19416

	namespace Framework\Syscrack\Game\Softwares;

	use Framework\Syscrack\Game\Bases\BaseSoftware;

	/**
	 * Class Package
	 * @package Framework\Syscrack\Game\Softwares
	 */
	class Package extends BaseSoftware
	{

		/**
		 * @param $softwareid
		 * @param $userid
		 * @param $computerid
		 *
		 * @return mixed|void
		 */

		public function onExecuted($softwareid, $userid, $computerid)
		{

			parent::onExecuted($softwareid, $userid, $computerid); // TODO: Change the autogenerated stub
		}

		/**
		 * @param $softwareid
		 * @param $userid
		 * @param $comptuerid
		 *
		 * @return mixed
		 */

		public function onInstalled($softwareid, $userid, $comptuerid)
		{

			return parent::onInstalled($softwareid, $userid, $comptuerid); // TODO: Change the autogenerated stub
		}
	}