<?php
	namespace Mods\Base\Views;

	use Framework\Views\BaseClasses\Page;

	class ModTest extends Page
	{

		public function mapping()
		{

			return [
				[
					'/modtest/', 'page'
				],
			];
		}

		public function page()
		{

			echo("If you are setting this message, then modding worked perfectly!");
		}

		public static function setup(bool $autoload=true, bool $session=true)
		{

			parent::setup($autoload, $session); // TODO: Change the autogenerated stub
		}
	}