<?php
	namespace Mods\Base\Views;

	use Framework\Views\BaseClasses\Page;

	class TestView extends Page
	{

		public function mapping()
		{

			return [
				[
					'/testview/', 'page'
				],
			];
		}

		public function page()
		{

			die("modding worked");
		}

		public static function setup(bool $autoload=true, bool $session=true)
		{

			parent::setup($autoload, $session); // TODO: Change the autogenerated stub
		}
	}