<?php
/**
 * Created by PhpStorm.
 * User: lewis
 * Date: 10/08/2018
 * Time: 03:05
 */

namespace Framework\Application\UtilitiesV2\Migrators;




class Log extends Base
{

    /**
     * @return mixed
     */

    public function migrate()
    {

        if( file_exists( SYSCRACK_ROOT . AUTOEXEC_LOG_LOCATION ) == false )
            mkdir( SYSCRACK_ROOT . AUTOEXEC_LOG_LOCATION );

        if( file_exists( SYSCRACK_ROOT . AUTOEXEC_LOG_LOCATION . "config.json") == false )
            file_put_contents( SYSCRACK_ROOT . AUTOEXEC_LOG_LOCATION . "config.json", json_encode([
                "file" => time()
            ]));

        return parent::migrate(); // TODO: Change the autogenerated stub
    }
}