<?php
	declare( strict_types=1 );
	/**
	 * Created by PhpStorm.
	 * User: newsy
	 * Date: 18/06/2019
	 * Time: 03:35
	 */

	namespace Framework\Application\UtilitiesV2\Jobs;


	use Framework\Syscrack\Game\Computer;
	use Framework\Syscrack\Game\Log;
	use Framework\Syscrack\Game\Software;

	class Reset extends Base
	{

		/**
		 * @var Computer
		 */

		protected static $computer;

		/**
		 * @var Software
		 */

		protected static $software;

		/**
		 * @var Log
		 */

		protected static $logs;

		/**
		 * Reset constructor.
		 */

		public function __construct()
		{

			if( isset( self::$computer ) == false )
				self::$computer = new Computer();

			if( isset( self::$software ) == false )
				self::$software = new Software();

			if( isset( self::$logs ) == false )
				self::$logs = new Log();
		}

		/**
		 * @param array $data
		 *
		 * @return bool
		 */

		public function execute(array $data): bool
		{

			$computers = self::$computer->getAllComputers();

			if( isset( $data["ignore"] ) )
				$ignore = $data["ignore"];
			else
				$ignore = [];

			foreach( $computers as $computer )
			{

				if( empty( $ignore ) == false )
					if( isset( $ignore[ $computer->type ] ) )
						continue;

				self::$computer->onComputerReset( $computer->type, $computer->computerid );
			}

			parent::execute($data); // TODO: Change the autogenerated stub
		}

		/**
		 * @return int
		 */

		public function frequency(): int
		{

			return( 60 * 60 * 2 );
		}
	}