<?php
/**
 * Created by PhpStorm.
 * User: lewis
 * Date: 05/08/2018
 * Time: 21:59
 */

namespace Framework\Application\UtilitiesV2\Tests;


use Framework\Application\UtilitiesV2\Container;

class Connection extends Base
{

    /**
     * @var \Colourspace\Database\Connection
     */

    protected $connection;

    /**
     * Connection constructor.
     */

    public function __construct()
    {

        if( Container::exist("application") == false )
            throw new \RuntimeException("no application");

        $this->connection = Container::get("application")->connection;
    }

    /**
     * @return bool
     * @throws \RuntimeException
     */

    public function execute()
    {

        if( @$this->connection->test() == false )
            return false;

        return parent::execute(); // TODO: Change the autogenerated stub
    }
}