<?php
/**
 * Created by PhpStorm.
 * User: lewis
 * Date: 05/08/2018
 * Time: 22:02
 */

namespace Framework\Application\UtilitiesV2\Tests;


class Resources extends Base
{

    /**
     * @return bool
     */

    public function execute()
    {

        return parent::execute(); // TODO: Change the autogenerated stub
    }
}