<?php
	declare(strict_types=1); //Created at %time% by %pid%

	namespace %namespace%;

	/**
	 * Class %classname%
	 * @package %namespace%
%globals%
	 */
	Class %classname%
	{

		protected $array = [];

		/**
		 * %class% constructor.
		 *
		 * @param $globals
		 */

		public function __construct( $globals ) {

			foreach( $globals as $global)
				$this->array[ $global[0] ] = $global[1];
		}

		/**
		 * @return array
		 */

		public function all()
		{

			return( $this->array );
		}

		/**
		 * @param $name
		 *
		 * @return mixed
		 */

		public function __get($name)
		{

			if( isset( $this->array[ $name ] ) == false )
				throw new \Error("Global " . $name . " does not exist");

			return($this->array[ $name ] );
		}
	}