<?php
	declare(strict_types=1); //Created at %time% by %pid% by %pid%

	namespace Framework\Views\Pages;

	use Framework\Views\BaseClasses\Page;

	/**
	 * Class %classname%
	 * @package %namespace%
	 */
	class %classname% extends Page
	{

		/**
		 * %classname% constructor.
		 *
		 * @param bool $requirelogin
		 * @param bool $update
		 * @param bool $admin_only
		 */

		public function __construct(bool $requirelogin = false, bool $update = true, bool $admin_only = false) { parent::__construct($requirelogin, $update, $admin_only); }

		/**
		 * %classname% constructor.
		 */

		public static function setup( $autoload = true, $session = true )
		{

			parent::setup(true, true);
		}

		/**
		 * @return array|mixed|void
		 */

		public function mapping()
		{

			parent::mapping();
		}
	}