<?php
	namespace _namespace_;

	/**
	 * Class _classname_
	 *
	 * Automatically created at: _time_
	 * @package _namespace_
	 */

	use Framework\Application\UtilitiesV2\Convention;

	class _classname_ extends Convention
	{

	    /**
	     * The syntax for requirements is as follows
	     *
	     *  "key" => "type"
	     *
	     * so for instance
	     *
	     *  "settings"  => "array"  : Specifies that this should be an array
	     *  "filename"  => "string" : Specifies that this should be a string
	     *  "admin"     => "bool"   : Specifies that this should be a bool
	     *  "admin"     => "int"    : Specifies that this should be a number
	     *  "dynamic"   => null     : Specifies that it is a "dynamic" field, thus may or may not have a value
	     * @var array
	     */

	    protected $requirements = [];
	}