<?php
	declare(strict_types=1); //Created at %time% by %pid% by %pid%

	namespace Framework\Views\Pages;

	use Framework\Views\BaseClasses\Page;

	/**
	 * Class %classname%
	 * @package %namespace%
	 */
	class %classname% extends Page
	{

		/**
		 * Ajax constructor.
		 */

		public function __construct()
		{

			parent::__construct(true, true );
		}

		/**
		 * @return array|mixed|void
		 */

		public function mapping()
		{

			parent::mapping();
		}
	}