<?php
	declare(strict_types=1); //Created at %time% by %pid%

	namespace %namespace%;

	use Framework\Application\UtilitiesV2\Collection;
	use Framework\Application\UtilitiesV2\Convention;
	use Framework\Application\UtilitiesV2\Conventions\EditableData;

	/**
	 * Class %classname%
	 * @package %namespace%
	 */
	class %classname% extends Collection
	{

	    /**
	     * %classname% constructor.
	     * @param $filepath
	     * @param $namespace
	     *
	     * @return bool
	     */

	    public function __construct( $filepath=null , $namespace=null, bool $auto_create = true)
	    {

	        if( $filepath == null )
	            $filepath = ""; //Enter Filepath

		    if( $namespace == null )
			    $filepath = ""; //Enter Filepath

	        parent::__construct( $filepath , $namespace, $auto_create);
	    }

	    /**
	     * Returns a new convention class.
	     * Remember to change the return type to the correct convention.
	     *
	     * @return array $values
	     * @return Convention
	     */

	    public static function dataInstance( $values )
	    {

	        return( new EditableData( $values ) );
	    }
	}