<?php
	declare(strict_types=1); //Created at 2019-06-11 03:15:41 by 19416

	namespace Framework\Syscrack\Game\Operations;

	use Framework\Syscrack\Game\Bases\BaseOperation;

	/**
	 * Class Extract
	 * @package Framework\Syscrack\Game\Operations
	 */
	class Extract extends BaseOperation
	{

		/**
		 * @param $timecompleted
		 * @param $computerid
		 * @param $userid
		 * @param $process
		 * @param array $data
		 *
		 * @return bool
		 */

		public function onCreation($timecompleted, $computerid, $userid, $process, array $data)
		{

			return parent::onCreation($timecompleted, $computerid, $userid, $process, $data); // TODO: Change the autogenerated stub
		}

		/**
		 * @param $timecompleted
		 * @param $timestarted
		 * @param $computerid
		 * @param $userid
		 * @param $process
		 * @param array $data
		 *
		 * @return bool|null|string
		 */

		public function onCompletion($timecompleted, $timestarted, $computerid, $userid, $process, array $data)
		{

			/**
			 * Put your code here
			 */

			if( parent::onCompletion(
				$timecompleted,
				$timestarted,
				$computerid,
				$userid,
				$process,
				$data) == false )
				return false;
			else if (isset($data['redirect']) == false)
				return true;
			else
				return ($data['redirect']);
		}
	}