<?php
	declare(strict_types=1);

	namespace Framework\Application\UtilitiesV2\Scripts;

	use Framework\Application\UtilitiesV2\Container;
	use Framework\Application;
	use Framework\Application\UtilitiesV2\Debug;

	/**
	 * Class _Refresh
	 *
	 * Automatically created at: 2019-06-03 08:27:32
	 * @package Framework\Application\UtilitiesV2\Scripts
	 */

	class _Refresh extends Base
	{

	    /**
	     * The logic of your script goes in this function.
	     *
	     * @param $arguments
	     * @return bool
	     */

	    public function execute($arguments)
	    {

		    if( Container::exist('instance') == false )
			    throw new \Error("Instance class missing from global container");

		    //Refresh
		    Container::get('instance')->refresh();

		    Debug::echo("Redefining Globals");
			Application::defineGlobals();
			Application\Settings::loadSettings();

		    return parent::execute($arguments); // TODO: Change the autogenerated stub
	    }

	    /**
	     * The help index can either be a string or an array containing a set of strings. You can only put strings in
	     * there.
	     *
	     * @return array
	     */

	    public function help()
	    {
	        return([
	            "arguments" => $this->requiredArguments(),
	            "help" => "Hello World"
	        ]);
	    }

	    /**
	     * Example:
	     *  [
	     *      "file"
	     *      "name"
	     *  ]
	     *
	     *  View from the console:
	     *      R file=myfile.php name=no_space
	     *
	     * @return array|null
	     */

	    public function requiredArguments()
	    {

	        return parent::requiredArguments();
	    }
	}