<?php
/**
 * Created by PhpStorm.
 * User: lewis
 * Date: 05/08/2018
 * Time: 23:53
 */

namespace Framework\Application\UtilitiesV2\Scripts;

use Framework\Application\UtilitiesV2\Container;
use Framework\Application\UtilitiesV2\Debug;
use Framework\Application\UtilitiesV2\Moderation;

class AutoUnban extends Base
{

    /**
     * @var Moderation
     */

    protected $moderation;

    /**
     * @param $arguments
     * @return bool
     * @throws \RuntimeException
     */

    public function execute($arguments)
    {

        if( Container::exist("application") == false )
            $this->initContainer();

        //Created after container init and we have database connection
        $this->moderation = new Moderation();

        if( Debug::isCMD() )
            Debug::echo("Removing bans", 3 );

        $audits = $this->moderation->all( AUDIT_TYPE_BAN );

        if( $audits->isEmpty() )
        {

            if( Debug::isCMD() )
                Debug::echo("No bans in system", 4 );

            return( true );
        }

        foreach( $audits as $audit )
        {


            if( Debug::isCMD() )
                Debug::echo("Checking ban: " . $audit->auditid, 4 );

            $metainfo = json_decode( $audit->metainfo );

            if( $metainfo->expires > time() )
            {

                if( Debug::isCMD() )
                    Debug::echo("Expired! Removing ban: " . $audit->auditid, 5 );

                $this->moderation->remove( $audit->auditit );
            }
        }

        if( Debug::isCMD() )
            Debug::echo("Finished removing bans", 3 );

        return parent::execute($arguments); // TODO: Change the autogenerated stub
    }

    /**
     * @return array
     */

    public function help()
    {
        return([
            "arguments" => $this->requiredArguments(),
            "help" => "Used in conjuction with automatic jobs to automatically unban any bans which are still active."
        ]);
    }
}