<?php
/**
 * Created by PhpStorm.
 * User: lewis
 * Date: 05/08/2018
 * Time: 22:03
 */

namespace Framework\Application\UtilitiesV2\Scripts;



use Framework\Application\UtilitiesV2\Container;


use Framework\Application\UtilitiesV2\Debug;
use Framework\Application\UtilitiesV2\Tests;

class AutoTest extends Base
{

    protected $tests;

    /**
     * AutoTest constructor.
     * @throws \RuntimeException
     */

    public function __construct()
    {

        $this->tests = new Tests( false );
    }

    /**
     * @param $arguments
     * @return bool
     * @throws \RuntimeException
     */

    public function execute($arguments)
    {

        if( Container::exist("application") == false )
            $this->initContainer();

        $this->tests->create();

        $result =  $this->tests->process();

        if( is_array( $result ) == false )
            return false;

        if( isset( $result["success"] ) == false )
            return false;

        if( $result["success"] == false )
        {

            if( Debug::isCMD() )
                Debug::echo( "Failed Test: " . $result["test"], 5 );

            return false;
        }

        return parent::execute($arguments); // TODO: Change the autogenerated stub
    }

    /**
     * @return array
     */

    public function help()
    {
        return([
            "arguments" => $this->requiredArguments(),
            "help" => "Runs through all tests and errors on fail, useful for grading Colourspace for public consumption."
        ]);
    }
}