<?php
	/**
	 * Created by PhpStorm.
	 * User: lewis
	 * Date: 07/08/2018
	 * Time: 04:06
	 */

	namespace Framework\Application\UtilitiesV2\Scripts;


	use Framework\Application\UtilitiesV2\Container;
	use Framework\Application\UtilitiesV2\Debug;
	use Framework\Application\UtilitiesV2\Scripts;

	class Commands extends Base
	{

		/**
		 * @param $arguments
		 *
		 * @return bool
		 * @throws \RuntimeException
		 */

		public function execute($arguments)
		{

			if (Container::exist("scripts") == false)
				throw new \RuntimeException("Scripts invalid");

			/** @var Scripts $scripts */
			$scripts = Container::get("scripts");
			$results = $scripts->scripts();

			if (isset($arguments["pretty"]) == false)
			{
				//Cute little hack to allow easier use with help
				$keys = array_keys($arguments);

				if (empty($keys) == false)
					if ($keys[0] == "pretty")
						$arguments["pretty"] = true;
			}

			if (isset($arguments["pretty"]) && $arguments["pretty"] != null)
			{

				if (Debug::isCMD())
					Debug::echo("Pretty printing results\n", 3);

				foreach ($results as $result)
				{

					if (Instance::$active_instance)
						Debug::echo(" " . $result);
					else
						Debug::echo(" php -f cmd/execute.php " . $result);
				}

				if (Debug::isCMD())
					if (Instance::$active_instance == false)
						Debug::echo("\n Execute php -f cmd/execute.php help [script] for specific help in regards to a script.\n");
					else
						Debug::echo("\n Execute help [script] for specific help in regards to a script.\n");
			}
			else
				if (Debug::isCMD())
					Debug::echo(print_r($results));

			return parent::execute($arguments); // TODO: Change the autogenerated stub
		}
	}