<?php
	declare(strict_types=1);

	namespace Framework\Application\UtilitiesV2\Scripts;

	/**
	 * Class Orange
	 *
	 * Automatically created at: 2018-09-01 19:45:02
	 */

	use Framework\Application\UtilitiesV2\Debug;


	/**
	 * Class Orange
	 * @package Framework\Application\UtilitiesV2\Scripts
	 */
	class Orange extends Base
	{

		/**
		 * @param $arguments
		 *
		 * @return bool
		 */
		public function execute($arguments)
		{

			Debug::echo("\nNow lets change this line of code");

			return parent::execute($arguments); // TODO: Change the autogenerated stub
		}

		/**
		 * @return array
		 */

		public function help()
		{
			return ([
				"arguments" => $this->requiredArguments(),
				"help" => "Sixtyten"
			]);
		}

		/**
		 * @return array|null
		 */

		public function requiredArguments()
		{

			return parent::requiredArguments();
		}
	}