<?php
	declare(strict_types=1); //Created at 2019-06-19 23:09:01 by 21284

	namespace Framework\Application\UtilitiesV2\Scripts;

	/**
	 * Class Pipeline
	 * @package Framework\Application\UtilitiesV2\Scripts
	 */
	class Pipeline extends Base
	{

		/**
		 * Sets up
		 */

		public static function setup()
		{

			if( isset( self::$piepline ) == false )
				self::$pipeline = new Pipeline();

			parent::setup();
		}

		/**
	     * The logic of your script goes in this function.
	     *
	     * @param $arguments
	     * @return bool
	     */

	    public function execute($arguments)
	    {

	    	if( isset( $arguments["job"] ) )
	    		$job = $arguments["job"];
	    	else
	    		$job == null;

	    	if( $job == null )


	        return parent::execute($arguments); // TODO: Change the autogenerated stub
	    }

	    /**
	     * The help index can either be a string or an array containing a set of strings. You can only put strings in
	     * there.
	     *
	     * @return array
	     */

	    public function help()
	    {
	        return([
	            "arguments" => $this->requiredArguments(),
	            "help" => "Hello World"
	        ]);
	    }

	    /**
	     * Example:
	     *  [
	     *      "file"
	     *      "name"
	     *  ]
	     *
	     *  View from the console:
	     *      Pipeline file=myfile.php name=no%space
	     *
	     * @return array|null
	     */

	    public function requiredArguments()
	    {

	        return parent::requiredArguments();
	    }
	}