<?php
	declare(strict_types=1);

	namespace Framework\Application\UtilitiesV2\Scripts;

	use Framework\Application;
	use Framework\Application\UtilitiesV2\Container;
	use Framework\Application\UtilitiesV2\Debug;

	/**
	 * Created by PhpStorm.
	 * User: lewis
	 * Date: 31/08/2018
	 * Time: 17:37
	 */
	class Refresh extends Base
	{

		/**
		 * @param $arguments
		 *
		 * @return bool
		 */

		public function execute($arguments)
		{

			if (Instance::$active_instance == false)
				throw new \Error("Needs an active instance");

			Debug::echo("Reinitializing application");

			//Remove the application
			Container::remove('application');

			$application = new Application( false );
			$application->prepare();

			//Add it back
			Container::add('application', $application );
			Container::get('application')->getScripts()->execute('_Refresh');

			return parent::execute($arguments); // TODO: Change the autogenerated stub
		}

		/**
		 * @return array
		 */

		public function help()
		{
			return ([
				"arguments" => $this->requiredArguments(),
				"help" => "Refreshes the instance, use this when you are developing new scripts. Once refreshed new classes will appear " .
					"however, you cannot modify the contents of a script then use refresh. it seems that PHP auto caches it when the instance is " .
					"created, so you'll have to restart your instance in order for code changes to have an effect!"
			]);
		}
	}