<?php
namespace Framework\Application\UtilitiesV2\Scripts;

/**
 * Class Settings
 *
 * Automatically created at: 2019-04-30 23:14:52
 */

use Framework\Application\UtilitiesV2\Scripts\Base;

class Settings extends Base
{

    /**
     * The logic of your script goes in this function.
     *
     * @param $arguments
     * @return bool
     */

    public function execute($arguments)
    {
        return parent::execute($arguments); // TODO: Change the autogenerated stub
    }

    /**
     * The help index can either be a string or an array containing a set of strings. You can only put strings in
     * there.
     *
     * @return array
     */

    public function help()
    {
        return([
            "arguments" => $this->requiredArguments(),
            "help" => "Hello World"
        ]);
    }

    /**
     * Example:
     *  [
     *      "file"
     *      "name"
     *  ]
     *
     *  View from the console:
     *      Settings file=myfile.php name=no_space
     *
     * @return array|null
     */

    public function requiredArguments()
    {

        return parent::requiredArguments();
    }
}