<?php
	namespace Framework\Application\UtilitiesV2\Scripts;

	/**
	 * Class Shell
	 *
	 * Automatically created at: 2019-05-30 01:31:25
	 * @package Framework\Application\UtilitiesV2\Scripts
	 */

	use Framework\Application\UtilitiesV2\Debug;
	use Framework\Application\UtilitiesV2\Container;

	class Shell extends Base
	{

	    /**
	     * The logic of your script goes in this function.
	     *
	     * @param $arguments
	     * @return bool
	     */

	    public function execute($arguments)
	    {

		    if( empty( Instance::$raw_line ) )
			    Debug::echo("Please enter something...");

		    if( strpos( Instance::$raw_line, 'shell') !== false )
			    $line = str_replace('shell','', Instance::$raw_line );
		    else
			    $line = Instance::$raw_line;

			Debug::echo( Container::get('scripts')->terminal( $line ) );

		    return parent::execute($arguments); // TODO: Change the autogenerated stub
	    }

	    /**
	     * The help index can either be a string or an array containing a set of strings. You can only put strings in
	     * there.
	     *
	     * @return array
	     */

	    public function help()
	    {
	        return([
	            "arguments" => $this->requiredArguments(),
	            "help" => "Executes a terminal operation. Dangerous if used with little to no understanding."
	        ]);
	    }

	    /**
	     * Example:
	     *  [
	     *      "file"
	     *      "name"
	     *  ]
	     *
	     *  View from the console:
	     *      Shell file=myfile.php name=no_space
	     *
	     * @return array|null
	     */

	    public function requiredArguments()
	    {

	        return parent::requiredArguments();
	    }
	}